### PR TITLE
fero: add travis setup

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Review by dm0- — COMMENTED** [review]
The build fix seems to work, but Travis is failing from `protoc` being too old.

**Comment by lucab** [comment]
@dm0- indeed. I'll need to tinker a bit more with to have all deps in place. I've split the fix in https://github.com/coreos/fero/pull/30 and will keep this WIP until travis will eventually work.

**Comment by lucab** [comment]
@dm0- this is now green, on both 1.27 and stable.

**Review by dm0- — APPROVED** [review]
Would it be simpler to switch the distro to 18.04 and use the packaged protoc v3 instead of manually extracting it?  Either way, LGTM

**Comment by lucab** [comment]
@dm0- is something fresher than trusty available on travis? I may have missed that. Unless you mean dist-upgrading from inside the test-job, in which case I'd rather not.

**Comment by dm0-** [comment]
Nevermind, it looks like they don't support newer distros (travis-ci/travis-ci#5821).

**Comment by lucab** [comment]
@dm0- do we need a new release with this to bump fero-client in the overlay?

**Comment by dm0-** [comment]
Yes, that is how we handle ebuilds for most of our other projects--bumping the version after tagging a release.  We have other projects that just bump the commit and ignore tagging, but since fero already has a 1.0, we should probably stick to that method.

**Pull request merged**
